[HUGGINGFACEHUB_API_TOKEN]
api_token = "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"
[PANDASAI_API_KEY]
api_key = "$2a$10$hWqNOQequTQUkZDYs8yk0eqiJJYB1HkwaAiN0rKXMXcJWbYzhsXxG"
[GOOGLE_GEMINI_API]
api_key = "AIzaSyDP-8bxUSkJ5R4kC1PaJ-vdocR4-T9usXE"
[OPENAI_API_KEY]
api_key = ""
[CLAUDE3_API_KEY]
api_key = ""
[GROQ_API_KEY]
api_key = "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"
[KANARIES_API_KEY]
api_key = "ak-8ba931749c567967242281f4a8a2736bfc7adf795c19e70e1b2cd02eba4c1e1e"
[ANTROPHIC_API_KEY]
api_key = ""
[TAVILY_API_KEY]
api_key = "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"
[ASSEMBLYAI_API_KEY]
api_key = "6b030bec2bf84229be185e2bd521a3c1"
[BING_API_KEY]
api_key = "ac104c3d81d94825b96220a9c7f63645"